<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="ChronicTest" skipped="0" failures="0" errors="3" tests="3" assertions="0" time="0.001446000300347805">
  <testcase name="test_cancel_scheduled_task" classname="ChronicTest" assertions="0" time="0.0012619998306035995">
    <error type="test_cancel_scheduled_task" message="ArgumentError: wrong number of arguments (given 2, expected 1)...">
Failure:
test_cancel_scheduled_task(ChronicTest) [/Users/jaspinwall/git/notifier/app/lib/task.rb:14]:
ArgumentError: wrong number of arguments (given 2, expected 1)
    app/lib/task.rb:14:in `schedule'
    test/lib/chronic_test.rb:14:in `test_cancel_scheduled_task'
    </error>
  </testcase>
  <testcase name="test_cancel_then_schedule_new" classname="ChronicTest" assertions="0" time="9.900005534291267e-05">
    <error type="test_cancel_then_schedule_new" message="ArgumentError: wrong number of arguments (given 2, expected 1)...">
Failure:
test_cancel_then_schedule_new(ChronicTest) [/Users/jaspinwall/git/notifier/app/lib/task.rb:14]:
ArgumentError: wrong number of arguments (given 2, expected 1)
    app/lib/task.rb:14:in `schedule'
    test/lib/chronic_test.rb:24:in `test_cancel_then_schedule_new'
    </error>
  </testcase>
  <testcase name="test_scheduled_task" classname="ChronicTest" assertions="0" time="8.50004144012928e-05">
    <error type="test_scheduled_task" message="ArgumentError: wrong number of arguments (given 2, expected 1)...">
Failure:
test_scheduled_task(ChronicTest) [/Users/jaspinwall/git/notifier/app/lib/task.rb:14]:
ArgumentError: wrong number of arguments (given 2, expected 1)
    app/lib/task.rb:14:in `schedule'
    test/lib/chronic_test.rb:6:in `test_scheduled_task'
    </error>
  </testcase>
</testsuite>
